<a href="https://colab.research.google.com/github/gasujina-prog/Python25Study/blob/main/numpy%EC%9D%B4%ED%95%B4%ED%95%B4%EB%B3%B4%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

#실수가 하나라도 있으면 실수로 통일.
a = np.array( [ 1, 2.3, 3, 4 ] )
a

array([1. , 2.3, 3. , 4. ])

In [3]:
#원래 정수형이 적용되어야 하나 왜인지 문자열로 적용이 됨...
a = np.array( [ 1, 2, '3', 4 ] )
a

array(['1', '2', '3', '4'], dtype='<U21')

In [4]:
#문자열과 정수의 갯수가 같으면 문자열로 통일
a = np.array( [ 1, '2', '3', 4 ] )
a

array(['1', '2', '3', '4'], dtype='<U21')

In [11]:
a = np.array( [ 1, 2, 3, 4 ] )
type(a)
a.dtype

dtype('int64')

In [12]:
#이거는 1차원 배열인 벡터(vector)
a = np.array( [ 1, 2, 3, 4 ] )
a

array([1, 2, 3, 4])

In [13]:
#이거는 2차원 배열인 매(마???)트릭스(Matrix)-행렬을 뜻한다.
a =np.array( [ [ 1, 2, 3, 4 ] , [ 5, 6, 7, 8 ] ] )
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
#이거는 3차원 배열인 텐소어(?) (Tensor)
#3차원 배열의 경우엔 헷갈릴 여지가 있는데 한줄 요약은 다음과 같다.
# "대괄호 3개가 있는 모양이 바로 3차원 배열"

#아래는 위키독스에서 이해를 돕기위한 내용이다.

#리스트안에 리스트가 3개 들어가있으면 3차원아니예요?
# a = [ [ 1 ] , [ 1 ] , [ 1 ] ]
#이렇게 헷갈린 친구들이 있을수 있어요.
# 정확히 리스트안에 리스트가 3개 들어가 있다는건 3행 1열의 2차원 배열을 뜻해요.
#3차원 배열은 [리스트 안에 - [리스트 안에 - [또 다른 리스트가 있는것]]]
#어후 뭔ㅋㅋ;;;
a =np.array( [ [ [ 1 ] , [ 1 ] ] , [ [ 1 ] , [ 1 ] ] , [ [ 1 ] , [ 1 ] ] ] )
a

array([[[1],
        [1]],

       [[1],
        [1]],

       [[1],
        [1]]])